<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\Store;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        $owner = User::where('email', 'admin@example.com')->first()
            ?? User::where('email', 'manager@example.com')->first()
            ?? User::first();

        if (! $owner) {
            $this->command?->warn('No users found; skipping ProductsSeeder.');

            return;
        }

        $store = Store::firstOrCreate(
            ['slug' => 'default-store'],
            ['owner_id' => $owner->id, 'name' => 'Default Store']
        );

        // Ensure we have some catalog refs to attach products to
        if (Category::count() === 0 || Brand::count() === 0) {
            $this->call(AdminCatalogSeeder::class);
        }

        $categories = Category::orderBy('id')->get(['id']);
        $brands = Brand::orderBy('id')->get(['id']);

        $names = [
            'High-Speed Diode',
            'Ceramic Capacitor 100nF',
            'Carbon Film Resistor 1kΩ',
            'DC Motor 12V',
            'Soldering Iron Tip',
            'MOSFET N-Channel',
            'Bridge Rectifier',
            'Relay Module 5V',
            'Voltage Regulator',
            'Heat Shrink Tube Set',
        ];

        foreach (range(1, 10) as $i) {
            $name = $names[$i - 1] ?? ('Product '.$i);
            $baseSlug = Str::slug($name);
            $slug = $baseSlug.'-'.Str::lower(Str::random(5));
            $sku = 'SKU-'.Str::upper(Str::random(8));

            Product::create([
                'store_id' => $store->id,
                'category_id' => $categories->random()->id,
                'brand_id' => $brands->random()->id,
                'name' => $name,
                'slug' => $slug,
                'sku' => $sku,
                'short_description' => 'Demo product generated by seeder.',
                'description' => 'This is a dummy product created for development/testing.',
                'price' => random_int(100, 5000) / 100,
                'compare_at' => random_int(0, 1) ? (random_int(100, 6000) / 100) : null,
                'unit' => random_int(0, 1) ? 'pcs' : null,
                'warranty_months' => random_int(0, 1) ? random_int(0, 24) : null,
                'is_published' => true,
                'published_at' => now(),
            ]);
        }
    }
}

