<?php

namespace App\Http\Controllers;

use Illuminate\Http\Response;

class FirebaseSwController extends Controller
{
    /**
     * Serve the Firebase Cloud Messaging service worker.
     *
     * The SW cannot read Vite env vars at runtime, so we inject the public web
     * config (config/services.firebase_web) here and serve it from the site root.
     * Handles background pushes and opens the order details page on click.
     */
    public function serviceWorker(): Response
    {
        $config = config('services.firebase_web');

        $firebaseConfig = json_encode([
            'apiKey' => $config['api_key'],
            'authDomain' => $config['auth_domain'],
            'projectId' => $config['project_id'],
            'storageBucket' => $config['storage_bucket'],
            'messagingSenderId' => $config['messaging_sender_id'],
            'appId' => $config['app_id'],
        ], JSON_UNESCAPED_SLASHES);

        $js = <<<JS
/* Firebase Cloud Messaging service worker (generated by FirebaseSwController) */
importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-messaging-compat.js');

const firebaseConfig = {$firebaseConfig};

if (firebaseConfig.apiKey && firebaseConfig.projectId) {
    firebase.initializeApp(firebaseConfig);
    const messaging = firebase.messaging();

    messaging.onBackgroundMessage((payload) => {
        const data = payload.data || {};
        const notification = payload.notification || {};
        const title = notification.title || data.title || 'New notification';
        const options = {
            body: notification.body || data.message || '',
            icon: '/favicon.ico',
            data: { link: data.link || '/' },
        };
        self.registration.showNotification(title, options);
    });
}

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    const link = (event.notification.data && event.notification.data.link) || '/';
    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            for (const client of clientList) {
                if ('focus' in client) {
                    client.navigate(link);
                    return client.focus();
                }
            }
            if (clients.openWindow) {
                return clients.openWindow(link);
            }
        })
    );
});
JS;

        return response($js, 200, [
            'Content-Type' => 'application/javascript',
            'Service-Worker-Allowed' => '/',
            'Cache-Control' => 'no-cache',
        ]);
    }
}
